# - Try to find the ZeroMQ library.

IF (ZMQ_INCLUDE_DIR AND ZMQ_LIBRARIES)
    # Already in cache, be silent
    SET(ZMQ_FIND_QUIETLY TRUE)
ENDIF (ZMQ_INCLUDE_DIR AND ZMQ_LIBRARIES)

FIND_PATH(ZMQ_INCLUDE_DIR zmq.h
    /usr/include
    /usr/local/include
)

FIND_LIBRARY(ZMQ_LIBRARY NAMES zmq PATHS
    /usr/lib
    /usr/local/lib
    /usr/lib64
    /usr/local/lib64
)

SET(ZMQ_LIBRARIES ${ZMQ_LIBRARY} CACHE STRING "The libraries needed to use ZMQ")

IF (ZMQ_INCLUDE_DIR AND ZMQ_LIBRARIES)
    SET(ZMQ_FOUND TRUE)
ENDIF (ZMQ_INCLUDE_DIR AND ZMQ_LIBRARIES)

IF (ZMQ_FOUND)
    IF (NOT ZMQ_FIND_QUIETLY)
        MESSAGE(STATUS "Found ZMQ: ${ZMQ_LIBRARIES}")
    ENDIF (NOT ZMQ_FIND_QUIETLY)
ELSE (ZMQ_FOUND)
    IF (ZMQ_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could NOT find ZMQ")
    ELSE (ZMQ_FIND_REQUIRED)
        MESSAGE(STATUS "Could NOT find ZMQ")
    ENDIF (ZMQ_FIND_REQUIRED)
ENDIF (ZMQ_FOUND)

MARK_AS_ADVANCED(ZMQ_INCLUDE_DIR ZMQ_LIBRARIES ZMQ_LIBRARY)
